# Generated by Django 4.1.7 on 2023-04-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table_date",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
            ],
        ),
        migrations.CreateModel(
            name="Table_groupname",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="群組名稱")),
            ],
        ),
        migrations.CreateModel(
            name="Table_project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="專案名稱")),
                ("status", models.BooleanField(verbose_name="狀態")),
            ],
        ),
        migrations.CreateModel(
            name="Table_shift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班別名稱")),
                ("time", models.CharField(max_length=100, verbose_name="班別時間")),
                ("charactor", models.CharField(max_length=1, verbose_name="白夜班")),
            ],
        ),
        migrations.CreateModel(
            name="Table_staff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("NTUHid", models.CharField(max_length=8, verbose_name="NTUH ID")),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("birthday", models.DateField(verbose_name="生日")),
            ],
        ),
        migrations.CreateModel(
            name="Table_Shift_Schedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_date",
                        verbose_name="日期",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_project",
                        verbose_name="專案",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_shift",
                        verbose_name="班別",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_staff",
                        verbose_name="人員",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_personal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time", models.CharField(max_length=100, verbose_name="時間")),
                ("name", models.CharField(max_length=100, verbose_name="事項名稱")),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_date",
                        verbose_name="日期",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_staff",
                        verbose_name="人員",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_meeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time", models.CharField(max_length=100, verbose_name="時間")),
                ("name", models.CharField(max_length=100, verbose_name="會議名稱")),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_date",
                        verbose_name="日期",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_staff",
                        verbose_name="人員",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_groups",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("turn", models.IntegerField(verbose_name="順序碼")),
                (
                    "groupname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_groupname",
                        verbose_name="群組名稱",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_staff",
                        verbose_name="人員",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_class",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time", models.CharField(max_length=100, verbose_name="時間")),
                ("name", models.CharField(max_length=100, verbose_name="課程名稱")),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_date",
                        verbose_name="日期",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.table_staff",
                        verbose_name="人員",
                    ),
                ),
            ],
        ),
    ]
