# Generated by Django 4.1.7 on 2023-04-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_table_staff_authid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table_shift_schedule",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.table_staff",
                verbose_name="人員",
            ),
        ),
    ]
