# Generated by Django 4.1.7 on 2023-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_table_groupname_turn_alter_table_class_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_groupname",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="順序碼"),
        ),
        migrations.AddField(
            model_name="table_groups",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="順序碼"),
        ),
    ]
