# Generated by Django 4.1.7 on 2023-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_alter_table_staff_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_project",
            name="turn",
            field=models.IntegerField(default=0, verbose_name="順序碼"),
        ),
        migrations.AlterField(
            model_name="table_groupname",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="優先碼"),
        ),
        migrations.AlterField(
            model_name="table_groups",
            name="priority",
            field=models.IntegerField(default=1, verbose_name="優先碼"),
        ),
        migrations.AlterField(
            model_name="table_groups",
            name="turn",
            field=models.IntegerField(default=0, verbose_name="順序碼"),
        ),
    ]
