# Generated by Django 4.1.7 on 2023-04-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_table_project_turn_alter_table_groupname_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_groupname",
            name="mod",
            field=models.IntegerField(default=0, verbose_name="同餘"),
        ),
        migrations.AddField(
            model_name="table_project",
            name="mod",
            field=models.IntegerField(default=0, verbose_name="同餘"),
        ),
        migrations.CreateModel(
            name="Table_project_attend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "constraint",
                    models.CharField(max_length=100, null=True, verbose_name="限制代碼"),
                ),
                ("sequence", models.IntegerField(default=0, verbose_name="順序碼")),
                (
                    "groupname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.table_groupname",
                        verbose_name="群組名稱",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.table_project",
                        verbose_name="專案",
                    ),
                ),
            ],
        ),
    ]
