# Generated by Django 4.1.7 on 2023-05-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_table_groupname_mod_table_project_mod_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table_rule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="規則名稱")),
                ("description", models.CharField(max_length=1000, verbose_name="規則描述")),
            ],
        ),
        migrations.CreateModel(
            name="Table_project_attend_rule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "project_attend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.table_project_attend",
                        verbose_name="專案群組",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.table_rule",
                        verbose_name="規則",
                    ),
                ),
            ],
        ),
    ]
