# Generated by Django 4.1.7 on 2023-05-07 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_alter_table_shift_charactor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table_extra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="超排名稱")),
                ("description", models.CharField(max_length=1000, verbose_name="超排描述")),
            ],
        ),
        migrations.CreateModel(
            name="Table_relax",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="減班名稱")),
                ("description", models.CharField(max_length=1000, verbose_name="減班描述")),
            ],
        ),
        migrations.CreateModel(
            name="Table_staff_relax",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "relax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.table_relax",
                        verbose_name="減班",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.table_staff",
                        verbose_name="人員",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_staff_extra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.table_extra",
                        verbose_name="超排",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.table_staff",
                        verbose_name="人員",
                    ),
                ),
            ],
        ),
    ]
