# Generated by Django 4.1.7 on 2023-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0013_table_extra_table_relax_table_staff_relax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_extra",
            name="staff_extra",
            field=models.ManyToManyField(
                through="app1.Table_staff_extra",
                to="app1.table_staff",
                verbose_name="人員",
            ),
        ),
        migrations.AddField(
            model_name="table_relax",
            name="staff_relax",
            field=models.ManyToManyField(
                through="app1.Table_staff_relax",
                to="app1.table_staff",
                verbose_name="人員",
            ),
        ),
    ]
