# Generated by Django 4.1.7 on 2023-05-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_table_extra_staff_extra_table_relax_staff_relax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table_extra",
            name="staff_extra",
            field=models.ManyToManyField(
                through="app1.Table_staff_extra", to="app1.table_staff"
            ),
        ),
        migrations.AlterField(
            model_name="table_relax",
            name="staff_relax",
            field=models.ManyToManyField(
                through="app1.Table_staff_relax", to="app1.table_staff"
            ),
        ),
    ]
