# Generated by Django 4.1.7 on 2023-05-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_table_staff_extra_credit_table_staff_relax_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table_staff_extra",
            name="extra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.table_extra",
                verbose_name="超排",
            ),
        ),
        migrations.AlterField(
            model_name="table_staff_extra",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.table_staff",
                verbose_name="人員",
            ),
        ),
        migrations.AlterField(
            model_name="table_staff_relax",
            name="relax",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.table_relax",
                verbose_name="減班",
            ),
        ),
        migrations.AlterField(
            model_name="table_staff_relax",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.table_staff",
                verbose_name="人員",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table_staff_extra",
            unique_together={("staff", "extra")},
        ),
        migrations.AlterUniqueTogether(
            name="table_staff_relax",
            unique_together={("staff", "relax")},
        ),
    ]
