# Generated by Django 4.1.7 on 2023-05-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_alter_table_staff_extra_extra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_rule",
            name="specialGroup",
            field=models.BooleanField(default=False, verbose_name="特殊編組規則"),
        ),
        migrations.AddField(
            model_name="table_rule",
            name="staffOnly",
            field=models.BooleanField(default=False, verbose_name="因人而異規則"),
        ),
        migrations.AddField(
            model_name="table_rule",
            name="valueOfRule",
            field=models.CharField(max_length=100, null=True, verbose_name="規則值"),
        ),
        migrations.AlterField(
            model_name="table_project_attend_rule",
            name="project_attend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.table_project_attend",
                verbose_name="專案群組",
            ),
        ),
        migrations.AlterField(
            model_name="table_project_attend_rule",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.table_rule",
                verbose_name="規則",
            ),
        ),
    ]
