# Generated by Django 4.1.7 on 2023-05-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_table_rule_specialgroup_table_rule_staffonly_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table_shift_charactor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="性質代碼")),
                ("charactor_time", models.CharField(max_length=5, verbose_name="白夜班")),
                (
                    "charactor_position",
                    models.CharField(max_length=5, verbose_name="位置"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="table_shift",
            name="charactor",
            field=models.CharField(max_length=5, null=True, verbose_name="白夜班"),
        ),
    ]
