# Generated by Django 4.1.7 on 2023-05-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_table_shift_charactor_alter_table_shift_charactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table_shift",
            name="charactor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.table_shift_charactor",
                verbose_name="班別性質",
            ),
        ),
    ]
